model_trainer:
  model_type: logistic_regression
  logistic_regression:
    C: 1.0
    max_iter: 1000
  

model_evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - roc_auc
    - pr_auc

  threshold: 0.5